### ISSUE TITLE
the pretrained model

### ISSUE THREAD

**Issue by xk-wang** [TUD-STKS/PyRCN#34]
where are the pretrained models?

**Comment by renierts** [comment]
Dear @xk-wang ,
We do not provide any pretrained models, since this would increase the repository. I can recommend you to download the Böck dataset and then train own models. The Jupyter Notebook (https://github.com/TUD-STKS/PyRCN/blob/master/examples/onset_detection.ipynb) is now updated so that it can give you a starting point. 

I will further update the notebook in the next weeks, since we have published a new onset paper. This will then include all steps to do all the parameter optimizations and evaluation steps. 

In the meantime, if you would like to optimize onset models, you can ask me any questions via mail (as you have done before)!

**Comment by xk-wang** [comment]
OK, Thank you @renierts sorry after a long time to reply.
